export default en = {
    delivered: 'DELIVERED',
    fastFood: 'FAST FOOD',
    toYour: 'TO YOUR',
    door: 'DOOR',
    setLocation: 'Set exact loaction to find the right',
    resturant: 'resturants near you.',
   
    //placeholders
    email: 'Email',
    password: 'Password',
    fullName: 'Full name',
    phone: 'Phone',
    age: 'Age',
  
    //error messages
  
    errorMessages: {
      emailErrorText: 'Enter valid email',
      forgetEmailErrorText: 'Enter valid email',
      passwordErrorText: 'Enter at least 6 digits',
      phoneNoErrorText: 'Enter valid number start with 0',
      nameErrorText: 'Choose your type',
      streetErrorText: 'Enter your address name',
      floorNoErrorText: 'Enter your floor number',
      buildingNoErrorText: 'Enter your build number',
      landMarkErrorText: 'Enter closest landmark',
      cityErrorText: 'Enter your city',
      AreaErrorText: 'Enter your area',
    },
  
    //screens name
    login: 'Login',
    signup: 'Sign up',
    backToLogin:'Back To Login',
    verifyingNumber: 'VerifyingNumber',
    phoneVerification: 'Email Verification',
    gotohome:'Go to Home',
    home: 'Home',
    addAddress: 'Add Address',
    cart: 'Cart',
    editAddress: 'Edit Address',
    editProfile: 'Edit Profile',
    menu: 'Menu',
    myAddresses: 'My Addresses',
    myOrders: 'My Orders',
    orderDetails: 'My Orders Details',
    offers: 'Offers',
    productDetails: 'Product Details',
    branches: 'Branches',
    profile: 'Profile',
    offersMenu: "Offers Menu",
    languages: 'Languages',
  
    //empty screens
    emptyCart: 'Cart is empty',
    emptyAddresses: 'Addresses is empty',
    emptyOrders: 'Orders is empty',
    emptyOffers: 'No offers',
  
    //Intro screen
    login: 'Login',
    facebook: 'Facebook',
    google: 'Google',
  
    //login screen
    welcomeBack: 'Welcome back',
    loginToAccount: 'Login to your account',
    forgetPassword: 'Forget your password?',
    dontHaveAccount: 'Dont have account? ',
    signup: 'Sign up',
    send: 'Send',
    alertsend:'Please check your email to reset password',
    errorMailmodal:"We can't find a user with that e-mail address.",

    //Reset Password
    resetPassword:'Reset Password',
  
    //signup screen
    createAccount: 'Create an account',
    byClicking: 'By clicking Sign up ypu agree to the following',
    terms: 'Terms and Conditions without reservation',
  
    //Home screen
    delivery: 'Delivery',
    or: 'Or',
    takeAway: 'Take away',
    useThisAddress: 'Use this address',
    edit: 'Edit',
  
    //verifyingNumber screen
    verifyingNumber: 'Verify your phone number',
    weHaveSentSMS: 'We have sent you an SMS with a code to number',
    orLogin: 'Or login with',
    socialNetwork: 'Social network',
    next: 'Next',
  
    // OTB screen screen
    phoneVerification: 'Email Verification',
    enterYourCode: 'Enter your OTP code here',
    didntReceivedCode: "Didn't received any code ?",
    resendCode: 'Resend a new code.',
    nextCode: 'Next',
    errorCode:'Please enter at least 6 numbers.',
  
    //add address screen
    enterDetails: 'Enter Details',
    editDetails: 'Edit Details',
    addressName: 'Address Name',
    floor: 'Floor No.',
    buildingNo: 'BuildingNo.',
    city: 'City',
    area: 'Area',
    landmark: 'Landmark',
    saveAddress: 'Save Address',
    name: "Street",
  
    //my addresses screen
    addNewAddress: 'Add new address',
    noAddresses: 'No Addresses',
    deleteAddress:'Do you want to delete this address?',
  
    //menu
    relatedOffers: 'Related offers',
    price: 'Price:',
    confirmOrder: 'Confirm Order',
    checkout: 'Checkout',
    exit:'Do you want to exit?',
    exitApp:'Exit App',
    yes:'Yes',
    no:'No',

    //branchCard
    workingHours: 'Working hours',
    from: 'From:',
    to: 'To:',
  
    //product details
    calories: 'Calories:',
    addToCart: 'Add to cart',
  
    //profile screen
    save: 'Save',
    cancel: 'Cancel',

     //languageSwitcher
    //  enLang: 'English',
     //Map screen 
    map:'Map Google',
    backMap:'Address Save',
    mapSave:'Get Address',
    locatemeMap:'Locate Me',

    gotohomepage: 'Go to Homepage',
    youarealready: 'You are already RBT Subscriber',
    addnewaddresssubscriber: 'Add new address subscriber',
    pleaseenteryourmobile: 'Please enter your mobile number to complete your login to the applicaiton',
    phonenumber: 'phone number',
    pleaseenteryourpwd: 'Please enter your password that received by sms.',
    enterphone: 'Enter phone',
    enteremail: 'Enter email',
    enterpassword:'Enter password',
    youarenotRBT: 'You are not RBT Subscriber.',
    pleaseenteryourmobileservice: 'Please enter your mobible number to complete your registration to the service',
    youwillreceive: 'You will receive password by sms',
    login: 'Login',
    yourcredit: 'Your credit 1500IQD',
    biweekly: 'Biweekly',
    weekly: 'Weekly',
    subscribe: 'Subscribe',
    top20tones: 'Top 20 tones',
    mostdown: 'Most down',
    search: 'Search',
    home: 'Home',
    language: 'Language',
    category: 'Category',
    profile: 'Profile',
    callerlist: 'Caller List',
    schedule: 'Schedule',
    unsubscribe: 'Unsubscribe',
    username: 'User Name',
    random: 'Random',
    songs: 'Songs',
    songname: 'Song name',
    songid: 'Song id',
    albumname: 'Album name',
    artistname: 'Artist name',
    pop: 'pop music',
    rock: 'Rock',
    islamic: 'Islamilc',
    rap: 'Rap',
    mylist: 'My List',
    cart: 'Cart',
    albums: 'Albums',
    album: 'Album',
    cancel: 'Cancel',
    favorites: 'Favorites',
    classic: 'Classic',

    iraqi: 'Iraqi',
    arabic: 'Arabic',
    kurdish: 'Kurdish',
    english: 'English',
    turkey: 'Turkey',
    others: 'Others',

    download: 'Download',
    mostdown: 'Most Down',
    gift: 'Gift',
    entername: 'Enter Name',
    enterfirstname: 'Enter Firstname',
    enterlastname:'Enter Lastname',
    aboutthesong: 'About the Song',
    addtomylist: 'Add to My List',
    confirm: 'Are you sure want to download?',
    ok:'Ok',
    remove:'Remove',
    removeconfirm: 'Are you sure want to remove?',
    favoriteconfirm: 'Are you sure want to add favorite list?',
    exitconfirm: 'Are you sure want to exit METREND?',
    exittitle: 'Confirm exit',
    offline:'offline',
    success:'success',
    selectlanguage: 'Change language',
    logout: 'Logout',
    passwordlength: 'Password must be at least 5 letters!',
    emailsyntaxerror: 'Email syntax error!',
    registersuccess: 'Registered successfully!',
    existemail: 'Already registered!',
    networkerror: 'Network error',
    userinfoincorrect: 'User info incorrect!',
    latestalbum: 'Latest Album',
    contents: 'Latest Contents',
    subcategories: 'Subcategories',
    artists: 'Artists',
    subscription: 'Subscription',
    forgotpwd: 'Forgot password?',
    mosttrending: 'Most Trending',
    arabicmosttrending: 'Arabic most trending',
    iraqimosttrending: 'Iraqi most trending'
  };