export const GET_QUIZ_META_INFO = "GET_QUIZ_META_INFO"
export const GET_QUIZ_CATEGORIES = 'GET_QUIZ_CATEGORIES'
export const ADD_TOPIC_TO_USER = "ADD_TOPIC_TO_USER"
export const GET_QUIZ_BY_CATEGORY = "GET_QUIZ_BY_CATEGORY"
export const QUIZ_COMPLETE = "QUIZ_COMPLETE"
export const CHALLENGE_USER_FOR_QUIZ = "CHALLENGE_USER_FOR_QUIZ"
