export const GET_USER_PROFILE = 'GET_USER_PROFILE'
export const EDIT_USER_PROFILE = 'EDIT_USER_PROFILE'
export const UPLOAD_USER_PHOTO = 'UPLOAD_USER_PHOTO'
export const UPDATE_PROFILE_IMAGE = 'UPDATE_PROFILE_IMAGE'
